openapi: 3.0.1
info:
  title: Products API
  description: API to manage products
  version: 1.0.0
servers:
  - url: http://localhost:8080
productsRouter:
  basePath: "/api/products"
  routes:
    - method: GET
      path: "/"
      description: "Traer todos los productos"
      queryParameters:
        limit:
          type: integer
          description: "Límite de productos por página"
          default: 10
        page:
          type: integer
          description: "Número de página"
          default: 1
        userQuery:
          type: string
          description: "Consulta personalizada del usuario"
        sortBy:
          type: string
          description: "Campo por el cual ordenar los productos"
      responses:
        200:
          description: "Retorna la lista de productos"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  playload:
                    type: array
                    items:
                      type: object
                    description: "Lista de productos"
                  totalPages:
                    type: integer
                    description: "Número total de páginas"
                  prevPage:
                    type: integer|string
                    description: "Página anterior o mensaje indicando que es la primera"
                  nextPage:
                    type: integer|string
                    description: "Página siguiente o mensaje indicando que es la última"
                  page:
                    type: integer
                    description: "Número de la página actual"
                  hasPrevPage:
                    type: boolean
                    description: "Indica si hay página anterior"
                  hasNextPage:
                    type: boolean
                    description: "Indica si hay página siguiente"
                  prevLink:
                    type: string|null
                    description: "Link a la página anterior"
                  nextLink:
                    type: string|null
                    description: "Link a la página siguiente"
        500:
          description: "Error del servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  error:
                    type: string
                    description: "Mensaje de error"

    - method: GET
      path: "/{pid}"
      description: "Filtrar productos por ID"
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: "ID del producto"
      responses:
        200:
          description: "Retorna el producto filtrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  playload:
                    type: object|null
                    description: "Producto filtrado o null si ID no válido"
                  error:
                    type: string|null
                    description: "Mensaje de error si ID no válido"
        500:
          description: "Error del servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  error:
                    type: string
                    description: "Mensaje de error"

    - method: POST
      path: "/newProduct"
      description: "Agregar un nuevo producto"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: "Cuerpo del nuevo producto a agregar"
      responses:
        200:
          description: "Retorna la lista de productos actualizada"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  playload:
                    type: array
                    items:
                      type: object
                    description: "Lista de productos"
        500:
          description: "Error al crear el producto"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  error:
                    type: string
                    description: "Mensaje de error"

    - method: PUT
      path: "/updateProduct/{pid}"
      description: "Actualizar un producto por ID"
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: "ID del producto a actualizar"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: "Cuerpo con los campos a actualizar"
      responses:
        200:
          description: "Retorna la lista de productos actualizada"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  playload:
                    type: array
                    items:
                      type: object
                    description: "Lista de productos"
        500:
          description: "Error al actualizar el producto"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  error:
                    type: string
                    description: "Mensaje de error"

    - method: DELETE
      path: "/deleteProduct/{pid}"
      description: "Eliminar un producto por ID"
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: "ID del producto a eliminar"
      responses:
        200:
          description: "Retorna la lista de productos actualizada"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: "Estado de la operación"
                  playload:
                    type: array
                    items:
                      type: object
                    description: "Lista de productos"
        500:
          description: "Error al eliminar el producto"
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    description: "Origen del servidor"
                  error:
                    type: string
                    description: "Mensaje de error"

  notFoundRoute:
    description: "Manejo de rutas no encontradas"
    responses:
      404:
        description: "Ruta no encontrada"
        content:
          application/json:
            schema:
              type: object
              properties:
                origin:
                  type: string
                  description: "Origen del servidor"
                error:
                  type: string
                  description: "Mensaje de error"
